### ISSUE TITLE
Android builds fail

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/otcurrent_pi#18]
[https://app.circleci.com/pipelines/github/Rasbats/otcurrent_pi/111/workflows/0af67547-a7c7-4a64-9d08-d919dd2d9f5f/jobs/1125](https://app.circleci.com/pipelines/github/Rasbats/otcurrent_pi/111/workflows/0af67547-a7c7-4a64-9d08-d919dd2d9f5f/jobs/1125)

**Comment by leamas** [comment]
This is nothing we can much about than to wait. Seems to be about overloaded docker.io servers. Rebuilding at some later point should hopefully work.

**Comment by Rasbats** [comment]
wxDatePickerCtrl and wxTimePickerCtrl are not recognised by Android. Sean had to make a new class for wxDatePickerCtrl in Climatology_pi. Dave steps around the issue in main OpenCPN.
Interesting GL stuff for Android by Sean:
[https://github.com/seandepagnier/climatology_pi](https://github.com/seandepagnier/climatology_pi)

**Comment by leamas** [comment]
One of these moments moments when I recognize things I have been aware of, but forgot. Sigh.

DatePicker/TimePicker: agreed.

As for the GL include files they should really be part of the Android setup, on other platforms they  should be available in various packages. While the OpenGL headers are pretty standardized, using headers from another source always carries a risk that they don't match the binaries.

**Comment by Rasbats** [comment]
The GL for Android affects a number of plugins. I am going to mess around with using stuff from Climatology_pi, which has successful Android builds.

**Comment by leamas** [comment]
Assuming you mean the include/GK headers. They are in a not that good location, should perhaps be better off in libs/AndroidHeaders or so.

**Comment by leamas** [comment]
I have a proposal at shipdriver, it should apply here as well. A bonus is that it does not involve any changes in CMakeLists.

**Comment by Rasbats** [comment]
Thanks for the libs/AndroidHeaders. This removed the graphics errors.
Now compiling for Android but .... installs and then crashes on enabling.
Need to work on the rendering, I think. 
At present there are two 'RenderOverlay's, GL and nonGL. Climatology uses just one.

**Comment by Rasbats** [comment]
Now builds for Android, with the latest ShipDriver template.
