### ISSUE TITLE
Settings window with high res display.

### ISSUE THREAD

**Issue by rgleason** [Rasbats/otcurrent_pi#19]
The new version is working well, I just have a few troubles with a high res display.
See pic below. 
It would be nice if the size of the calendar was remembered.  Also the width of the calendar is a little too squeezed, I reallize you can scroll to the next month but the arrows dont really show.

Also the selection for the tidal data covers the actual file selected and the file selected window isn't quite high enough.
![Screenshot (118)](https://user-images.githubusercontent.com/2363959/143934266-28431e75-1a02-4534-a830-9506b742df54.png)

Can still use the plugin!

**Comment by rgleason** [comment]
See jon's recent changes to ocpn_draw

**Comment by Rasbats** [comment]
@rgleason : Could you give this a test? Removed some hard-codes sizes.
[https://cloudsmith.io/~opencpn/repos/otcurrent-alpha/packages/?q=*msvc*](https://cloudsmith.io/~opencpn/repos/otcurrent-alpha/packages/?q=*msvc*)

**Comment by Rasbats** [comment]
Did you try to drag the dialog bigger? The size should be remembered.

**Comment by rgleason** [comment]
This is very good!  Thank you
![otCurrent](https://user-images.githubusercontent.com/2363959/146035088-f5e46d1b-aa15-4d01-98c1-c5dd6f44a2b9.png)
u

**Comment by rgleason** [comment]
The dialog size is always opened at the same size, it appears.  Even when I close the menu and close Opencpn and then reopen.
This is the size it opens at.
![Screenshot (137)](https://user-images.githubusercontent.com/2363959/146036234-665a26d4-9ec2-4e9a-9474-2b81f16f2ab9.png)

**Comment by rgleason** [comment]
I can resize in this way, but when closed, it will open to the bigger menu
![Screenshot (138)](https://user-images.githubusercontent.com/2363959/146036564-8d922aea-a5b3-46b5-b201-696dea59301d.png)

**Comment by Rasbats** [comment]
The size of that dialog is not retained. Will take a look later.

**Comment by rgleason** [comment]
Thanks MIke

**Comment by Rasbats** [comment]
>This is very good! Thank you

The plugin is not connected to a graph of tidal currents. That is in core OpenCPN. Is otcurrent resizing ok and retaining size?

**Comment by rgleason** [comment]
Ok, this morning, using the most current 3.1.0 version. 

I found that clicking on the toolbar "Current" arrow that the screen pops up in the same place to the upper left every time at the previously adjusted size.  The Calendar seems to pop up at the same small size every time. Don't know the intent here, but there are a couple of problems.  I can't see the "Select Tidlal Data Folder" line of text in the window on the preferences menu.  Also the Calendar is not shown completely when resized bigger and the left and right arrows are cut off.  See attached pics.

When right clicking on the current arrows I found the menu always popped up at the same size whether I resized it or not. It works and is useable, I don't know what the intent is. I wonder if the size of this popup is too big for small res screens. Please see pics too

![cur1](https://user-images.githubusercontent.com/2363959/146212658-cf5cc965-fa4a-431d-a667-ba20b4bab51a.png)
![cur2](https://user-images.githubusercontent.com/2363959/146212673-7c5688d5-1b32-4d0e-a7bf-cd5d9f946992.png)
![cur3](https://user-images.githubusercontent.com/2363959/146212688-4cdd2061-be53-4159-8656-cbfe25c7330d.png)
![cur4](https://user-images.githubusercontent.com/2363959/146212694-e5373c8c-bf83-4bba-bb61-bc53039323de.png)
![cur5](https://user-images.githubusercontent.com/2363959/146212697-3ed62dc0-f5e8-4dec-b98c-429ae3960952.png)
![cur6](https://user-images.githubusercontent.com/2363959/146212707-81c0e896-2f11-4df8-ba34-f82e2e53761a.png)
![cur7](https://user-images.githubusercontent.com/2363959/146212720-0f4cd975-1b28-48b0-8f2d-9e85a52694fa.png)

**Comment by Rasbats** [comment]
The version to test is here:
[https://cloudsmith.io/~opencpn/repos/otcurrent-alpha/packages/?q=msvc](https://cloudsmith.io/~opencpn/repos/otcurrent-alpha/packages/?q=msvc)
Is this the one used for the pics?

**Comment by rgleason** [comment]
Now downloaded  and installed.
otcurrent-3.1-msvc-10.0.14393-tarball==3.1.0+219.04bfe6b

**Comment by rgleason** [comment]
This version is better with regard to seeing the Tidal Data Folder, and that menu retains the size selected.
The popup calendar is small, and when resized bigger, we still do not see the full calendar and the buttons on either side to move from month to month.


![Screenshot (150)](https://user-images.githubusercontent.com/2363959/146219476-58dba117-ec3f-4a66-9e82-5351f75c9672.png)
![Screenshot (151)](https://user-images.githubusercontent.com/2363959/146219591-8693ad40-52e2-45f6-9e27-18eb4f961085.png)


The Current popup menus are  all at some set size, even when resized as in the previous version. Don't know the intention here.

**Comment by Rasbats** [comment]
This is how it looks for me after enlarging the calendar. Buttons for monthly move are small but present.
The intention is to have a calendar that works on all OS, including Android.
![calendar](https://user-images.githubusercontent.com/2537240/146221470-7b6108c7-93a4-4e2f-8c83-f10c4d7cf21e.jpg)

**Comment by rgleason** [comment]
That is not the way it is with mine as seen in the attached screenshots.  I wonder why.  In the second pic I have stretched it out and the calendar does not fully show.  Frustratrating isn't it?  I can live with it.

**Comment by rgleason** [comment]
This is old. I am closing it.
