### ISSUE TITLE
RFE: Windows High DPI Resolution response

### ISSUE THREAD

**Issue by rgleason** [Rasbats/otcurrent_pi#20]
Mike, otcurrent is excellent as ever.  There is just on or two things that need to be improved.
Bdbcat has some code to make the text DPI responsive for Windows. You could use that for the Tide direction and speed as shown at each arrow.

![otcurrent-text-size](https://github.com/Rasbats/otcurrent_pi/assets/2363959/e5a1008b-c56d-4e74-bdb9-bca5deb05688)

**Comment by Rasbats** [comment]
Can you point me to the code needed? Thanks. Assume you have tried the option in preferences.

**Comment by rgleason** [comment]
I did not see an option to change text size in prefs. Just back from cruise will check again and try to find some example code

**Comment by rgleason** [comment]
Found the High Resolution button, it seems to separate the text vertically but does not increase Font size.
I also tried changing the various User Scale Factors and they do not control the text size either.


![Current2](https://github.com/Rasbats/otcurrent_pi/assets/2363959/d5253dad-590b-46e6-a2cd-9ab9c65ef419)

![Current1](https://github.com/Rasbats/otcurrent_pi/assets/2363959/47cec486-380b-4303-9a99-72d8192e6157)

**Comment by rgleason** [comment]
Mike hopefully the links in this post will help.  These were used to get Dashboard working for High Resolution High DPI Displays that are more often used these days.
https://github.com/antipole2/JavaScript_pi/issues/60#issuecomment-1476484418

DB: Preferences. Scale instr.list and +- icons #2983 [6a356104a63](https://github.com/OpenCPN/OpenCPN/commit/6a356104a637cfa45a9b1f75c583afea5e7df29c)

DB: Dialog "Add Instrument". Increase size to half Canvas hight #2983 [7fd1b159543](https://github.com/OpenCPN/OpenCPN/commit/7fd1b159543f3b22110e2d81e04b0330b6e24dd3)

DB: Preferences. Scale instr.list and +- icons https://github.com/OpenCPN/OpenCPN/issues/2983 [43a64cad1b3](https://github.com/OpenCPN/OpenCPN/commit/43a64cad1b3)

DB: Win Scaled fonts and sizing [eb3b73acce2](https://github.com/OpenCPN/OpenCPN/commit/eb3b73acce2)

Added this reference item for examples for other plugins to follow.
https://github.com/OpenCPN/plugins/issues/942

**Comment by Rasbats** [comment]
Found Dave's correction for MSW in ocpn_draw. Alpha packages here:
[https://cloudsmith.io/~opencpn/repos/otcurrent-alpha/packages/](https://cloudsmith.io/~opencpn/repos/otcurrent-alpha/packages/)
@rgleason : Please can you test.

**Comment by rgleason** [comment]
MIke, I will test, but can you point me to those corrections?  I would like to bookmark them!

**Comment by Rasbats** [comment]
[https://github.com/Rasbats/otcurrent_pi/commit/1716808bf89061b86a9ee7612e73e642e0e3164c](https://github.com/Rasbats/otcurrent_pi/commit/1716808bf89061b86a9ee7612e73e642e0e3164c)

**Comment by rgleason** [comment]
MIke, this is considerably better. Is there a way to increase the line spacing?   Also what Opencpn  Options > User > Font name controls this?

**Comment by rgleason** [comment]
![Screenshot (1703)](https://github.com/Rasbats/otcurrent_pi/assets/2363959/4ad45c8a-d1f4-4988-96fe-48d82de55a2a)

**Comment by Rasbats** [comment]
Line spacing can be increased with:
Preference/High Resolution Display

**Comment by Rasbats** [comment]
Font size is hard-coded. OpenCPN options cannot change this.

**Comment by rgleason** [comment]
What I am showing has High Res checked. Line spacing is inadequate. Also text is a little too bold IMHO

**Comment by Rasbats** [comment]
Package build with fontweight normal and line spacing increased from 26->35.

**Comment by rgleason** [comment]
Thanks MIke, much better now with High Res checked.
![Screenshot (1715)](https://github.com/Rasbats/otcurrent_pi/assets/2363959/326f1311-0356-4583-b55c-4cfb3e9157fd)
