### ISSUE TITLE
RFE:  Smaller menu interface.

### ISSUE THREAD

**Issue by rgleason** [Rasbats/otcurrent_pi#21]
Allow user to adjust the interface to take up less space, by reorganizing the menu with the left and right arrows towards the top.  See the pic.

![otcurrent-menu-interface](https://github.com/Rasbats/otcurrent_pi/assets/2363959/6388ea33-87f4-4025-8b27-6554d340851a)

**Comment by Rasbats** [comment]
Now fixed in the alpha package. 
[https://cloudsmith.io/~opencpn/repos/otcurrent-alpha/packages/](https://cloudsmith.io/~opencpn/repos/otcurrent-alpha/packages/)

**Comment by rgleason** [comment]
Great. Thanks closing
