### ISSUE TITLE
Linux does not have GL/GL.h

### ISSUE THREAD

**Issue by nkiesel** [Rasbats/otcurrent_pi#7]
Hi,

should that include in `otcurrentOverlayFactory.h` not be `"GL/gl.h"`?  That is provided by `mesa-common-dev` on my Debian machine.  I changed it and after that, it compiled and installed.

Still have not been able to make it work though (configures, but does not show any arrows although harmonics file is in right place).

**Comment by Rasbats** [comment]
Tks,
Yes, my mistake. Which harmonics are you using? I suggest a test with the ones from the standard installation, looking at the USA (usr/share/opencpn/tcdata). Zoom in to a scale of about 85000 or more.

**Comment by nkiesel** [comment]
All working now.  Perhaps I was just at the wrong zoom level.  Nice, thanks for this!
